apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        component: db
    spec:
      containers:
        - name: mysql-container
          image: 244069240907.dkr.ecr.us-east-1.amazonaws.com/docker-containers-db:v1.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: passsword
          ports:
            - containerPort: 3306